import Head from "next/head";
import Form from "../components/Form";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dbConnect from "../middleware/database";

export default function Home() {
  return (
    <div className="bg-gray-900 min-h-screen flex flex-col	justify-center items-center	">
      <Head>
        <title>InnerNote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center w-1/2 flex flex-col	justify-center items-center">
        <p className="font-bold text-white lg:text-6xl mb-4 pb-3 my-auto py-8 title">
          Express yourself safely with InnerNote. <br />
          <span className="title lg:text-2xl">
            and dive deep into other people's minds
          </span>
        </p>
        <span className="mb-3 text-blue-600 cursor-pointer hover:underline">
          <Link href="/notes">
            <a>browse all InnerNotes →</a>
          </Link>
        </span>
        <Form />
      </main>
    </div>
  );
}
