import React from "react";
import Head from "next/head";
import Link from "next/link";
import Table from "../../components/Table";

export default function InnerNotes() {
  return (
    <div className="bg-gray-900 min-h-screen flex flex-col	justify-center  items-center	overflow-hidden">
      <Head>
        <title>InnerNote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my-8">
        <p className="font-bold text-white lg:text-6xl mb-4 pb-2 my-auto py-1 text-center">
          Explore all the InnerNotes!
        </p>
        <span className="my-auto py-1 text-center text-blue-600 cursor-pointer hover:underline ">
          <Link href="/" className="text-center mb-4">
            <a className="text-center mb-4">← back to homepage</a>
          </Link>
        </span>
        <Table className="mb-4 pb-4" />
      </main>
    </div>
  );
}
